name: amazon_cognito_identity_dart
version: 0.0.22
author: Jon Saw <jon.saw@gmail.com>
homepage: https://github.com/jonsaw/amazon-cognito-identity-dart/tree/master
description: Unofficial Amazon Cognito Identity Provider Dart SDK,
  to easily add user sign-up and sign-in to your mobile and web apps
  with AWS Cloud Services.

environment:
  sdk: '>=2.10.5 <3.0.0'

dependencies:
  convert: ^3.0.0
  crypto: ^3.0.1
  http: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.4.0

